spring:
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB
  datasource:
    url: jdbc:h2:file:./data/mradopcionesdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  application:
    name: mradopciones-backend
app:
  jwt:
    secret: ${JWT_SECRET:CLAVESUPERSECREATADDASASKSLADJAS}
    expiration-ms: 86400000
  uploads-dir: ./uploads